import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch "The Human Archive" design system tokens
        "primary-container":        "#7c3aed",
        "primary":                  "#630ed4",
        "primary-fixed":            "#eaddff",
        "primary-fixed-dim":        "#d2bbff",
        "on-primary":               "#ffffff",
        "on-primary-fixed":         "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary":          "#d2bbff",
        "on-primary-container":     "#ede0ff",
        "secondary":                "#5d5c74",
        "secondary-container":      "#e2e0fc",
        "secondary-fixed":          "#e2e0fc",
        "secondary-fixed-dim":      "#c6c4df",
        "on-secondary":             "#ffffff",
        "on-secondary-fixed":       "#1a1a2e",
        "on-secondary-fixed-variant":"#45455b",
        "on-secondary-container":   "#63627a",
        "tertiary":                 "#005479",
        "tertiary-container":       "#006d9c",
        "tertiary-fixed":           "#c9e6ff",
        "tertiary-fixed-dim":       "#89ceff",
        "on-tertiary":              "#ffffff",
        "on-tertiary-container":    "#cfe9ff",
        "on-tertiary-fixed":        "#001e2f",
        "on-tertiary-fixed-variant":"#004c6e",
        "surface":                  "#fcf9f8",
        "surface-bright":           "#fcf9f8",
        "surface-dim":              "#dcd9d9",
        "surface-variant":          "#e5e2e1",
        "surface-tint":             "#732ee4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f6f3f2",
        "surface-container":        "#f0edec",
        "surface-container-high":   "#ebe7e7",
        "surface-container-highest":"#e5e2e1",
        "on-surface":               "#1c1b1b",
        "on-surface-variant":       "#4a4455",
        "inverse-surface":          "#313030",
        "inverse-on-surface":       "#f3f0ef",
        "background":               "#fcf9f8",
        "on-background":            "#1c1b1b",
        "outline":                  "#7b7487",
        "outline-variant":          "#ccc3d8",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
      },
      fontFamily: {
        "headline": ["Bricolage Grotesque", "sans-serif"],
        "body":     ["Geist Sans", "sans-serif"],
        "label":    ["Geist Sans", "sans-serif"],
      },
      borderRadius: {
        "card":    "1.5rem",
        "card-lg": "2.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
